version: "3.9"
services:
  caddy:
    image: caddy:2
    configs:
    - source: caddyfile
      target: /etc/caddy/Caddyfile
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: ingress
    - target: 443
      published: 443
      protocol: tcp
      mode: ingress
    volumes:
    - caddy:/data

  migration:
    image: wearepal/landscapes:4.0.1
    command: bin/run-migrations
    secrets:
    - secret_key_base
    - database_url
    - redis_url
    deploy:
      restart_policy:
        condition: none

  web:
    image: wearepal/landscapes:4.0.1
    command: bin/run-server
    secrets:
    - secret_key_base
    - database_url
    - redis_url
    - source: storage
      target: /app/config/storage.yml

  worker:
    image: wearepal/landscapes:4.0.1
    command: bin/run-worker
    stop_signal: SIGQUIT
    secrets:
    - secret_key_base
    - database_url
    - redis_url
    - source: storage
      target: /app/config/storage.yml

configs:
  caddyfile:
    external: true
    name: landscapes_caddyfile

secrets:
  secret_key_base:
    external: true
    name: landscapes_secret_key_base
  database_url:
    external: true
    name: landscapes_database_url
  redis_url:
    external: true
    name: landscapes_redis_url
  storage:
    external: true
    name: landscapes_storage

volumes:
  caddy:
