common: &default_settings
  app_name: SSRP Web Application
  log_level: info


development:
  <<: *default_settings
  app_name: SSRP Web Application (Development)

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: SSRP Web Application (Staging)

production:
  <<: *default_settings
